# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.9
#
# <auto-generated>
#
# Generated from file `Robot.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module SmartHouse
_M_SmartHouse = Ice.openModule('SmartHouse')
__name__ = 'SmartHouse'

if 'TimeOfDay' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.TimeOfDay = Ice.createTempClass()
    class TimeOfDay(object):
        def __init__(self, hour=0, minute=0, second=0):
            self.hour = hour
            self.minute = minute
            self.second = second

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.hour)
            _h = 5 * _h + Ice.getHash(self.minute)
            _h = 5 * _h + Ice.getHash(self.second)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_SmartHouse.TimeOfDay):
                return NotImplemented
            else:
                if self.hour is None or other.hour is None:
                    if self.hour != other.hour:
                        return (-1 if self.hour is None else 1)
                else:
                    if self.hour < other.hour:
                        return -1
                    elif self.hour > other.hour:
                        return 1
                if self.minute is None or other.minute is None:
                    if self.minute != other.minute:
                        return (-1 if self.minute is None else 1)
                else:
                    if self.minute < other.minute:
                        return -1
                    elif self.minute > other.minute:
                        return 1
                if self.second is None or other.second is None:
                    if self.second != other.second:
                        return (-1 if self.second is None else 1)
                else:
                    if self.second < other.second:
                        return -1
                    elif self.second > other.second:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHouse._t_TimeOfDay)

        __repr__ = __str__

    _M_SmartHouse._t_TimeOfDay = IcePy.defineStruct('::SmartHouse::TimeOfDay', TimeOfDay, (), (
        ('hour', (), IcePy._t_short),
        ('minute', (), IcePy._t_short),
        ('second', (), IcePy._t_short)
    ))

    _M_SmartHouse.TimeOfDay = TimeOfDay
    del TimeOfDay

if 'OutOfEnergyException' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.OutOfEnergyException = Ice.createTempClass()
    class OutOfEnergyException(Ice.UserException):
        def __init__(self, errorTime=Ice._struct_marker, message="Cannot perform movement - robot does not have enough energy."):
            if errorTime is Ice._struct_marker:
                self.errorTime = _M_SmartHouse.TimeOfDay()
            else:
                self.errorTime = errorTime
            self.message = message

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHouse::OutOfEnergyException'

    _M_SmartHouse._t_OutOfEnergyException = IcePy.defineException('::SmartHouse::OutOfEnergyException', OutOfEnergyException, (), False, None, (
        ('errorTime', (), _M_SmartHouse._t_TimeOfDay, False, 0),
        ('message', (), IcePy._t_string, True, 1)
    ))
    OutOfEnergyException._ice_type = _M_SmartHouse._t_OutOfEnergyException

    _M_SmartHouse.OutOfEnergyException = OutOfEnergyException
    del OutOfEnergyException

if 'InvalidPositionException' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.InvalidPositionException = Ice.createTempClass()
    class InvalidPositionException(Ice.UserException):
        def __init__(self, errorTime=Ice._struct_marker, message="Cannot set new position - invalid position value."):
            if errorTime is Ice._struct_marker:
                self.errorTime = _M_SmartHouse.TimeOfDay()
            else:
                self.errorTime = errorTime
            self.message = message

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHouse::InvalidPositionException'

    _M_SmartHouse._t_InvalidPositionException = IcePy.defineException('::SmartHouse::InvalidPositionException', InvalidPositionException, (), False, None, (
        ('errorTime', (), _M_SmartHouse._t_TimeOfDay, False, 0),
        ('message', (), IcePy._t_string, True, 2)
    ))
    InvalidPositionException._ice_type = _M_SmartHouse._t_InvalidPositionException

    _M_SmartHouse.InvalidPositionException = InvalidPositionException
    del InvalidPositionException

if 'RobotNotActiveException' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.RobotNotActiveException = Ice.createTempClass()
    class RobotNotActiveException(Ice.UserException):
        def __init__(self, errorTime=Ice._struct_marker, message="Cannot perform action - robot is not active."):
            if errorTime is Ice._struct_marker:
                self.errorTime = _M_SmartHouse.TimeOfDay()
            else:
                self.errorTime = errorTime
            self.message = message

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHouse::RobotNotActiveException'

    _M_SmartHouse._t_RobotNotActiveException = IcePy.defineException('::SmartHouse::RobotNotActiveException', RobotNotActiveException, (), False, None, (
        ('errorTime', (), _M_SmartHouse._t_TimeOfDay, False, 0),
        ('message', (), IcePy._t_string, True, 3)
    ))
    RobotNotActiveException._ice_type = _M_SmartHouse._t_RobotNotActiveException

    _M_SmartHouse.RobotNotActiveException = RobotNotActiveException
    del RobotNotActiveException

if 'RobotAlreadyActiveException' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.RobotAlreadyActiveException = Ice.createTempClass()
    class RobotAlreadyActiveException(Ice.UserException):
        def __init__(self, errorTime=Ice._struct_marker, message="Cannot activate robot - robot is already active."):
            if errorTime is Ice._struct_marker:
                self.errorTime = _M_SmartHouse.TimeOfDay()
            else:
                self.errorTime = errorTime
            self.message = message

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::SmartHouse::RobotAlreadyActiveException'

    _M_SmartHouse._t_RobotAlreadyActiveException = IcePy.defineException('::SmartHouse::RobotAlreadyActiveException', RobotAlreadyActiveException, (), False, None, (
        ('errorTime', (), _M_SmartHouse._t_TimeOfDay, False, 0),
        ('message', (), IcePy._t_string, True, 4)
    ))
    RobotAlreadyActiveException._ice_type = _M_SmartHouse._t_RobotAlreadyActiveException

    _M_SmartHouse.RobotAlreadyActiveException = RobotAlreadyActiveException
    del RobotAlreadyActiveException

if 'Movement' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.Movement = Ice.createTempClass()
    class Movement(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    Movement.UP = Movement("UP", 0)
    Movement.DOWN = Movement("DOWN", 1)
    Movement.LEFT = Movement("LEFT", 2)
    Movement.RIGHT = Movement("RIGHT", 3)
    Movement._enumerators = { 0:Movement.UP, 1:Movement.DOWN, 2:Movement.LEFT, 3:Movement.RIGHT }

    _M_SmartHouse._t_Movement = IcePy.defineEnum('::SmartHouse::Movement', Movement, (), Movement._enumerators)

    _M_SmartHouse.Movement = Movement
    del Movement

if 'Position' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.Position = Ice.createTempClass()
    class Position(object):
        def __init__(self, x=0.0, y=0.0):
            self.x = x
            self.y = y

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_SmartHouse.Position):
                return NotImplemented
            else:
                if self.x != other.x:
                    return False
                if self.y != other.y:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHouse._t_Position)

        __repr__ = __str__

    _M_SmartHouse._t_Position = IcePy.defineStruct('::SmartHouse::Position', Position, (), (
        ('x', (), IcePy._t_float),
        ('y', (), IcePy._t_float)
    ))

    _M_SmartHouse.Position = Position
    del Position

_M_SmartHouse._t_Robot = IcePy.defineValue('::SmartHouse::Robot', Ice.Value, -1, (), False, True, None, ())

if 'RobotPrx' not in _M_SmartHouse.__dict__:
    _M_SmartHouse.RobotPrx = Ice.createTempClass()
    class RobotPrx(Ice.ObjectPrx):

        def isActive(self, context=None):
            return _M_SmartHouse.Robot._op_isActive.invoke(self, ((), context))

        def isActiveAsync(self, context=None):
            return _M_SmartHouse.Robot._op_isActive.invokeAsync(self, ((), context))

        def begin_isActive(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_isActive.begin(self, ((), _response, _ex, _sent, context))

        def end_isActive(self, _r):
            return _M_SmartHouse.Robot._op_isActive.end(self, _r)

        def getEnergy(self, context=None):
            return _M_SmartHouse.Robot._op_getEnergy.invoke(self, ((), context))

        def getEnergyAsync(self, context=None):
            return _M_SmartHouse.Robot._op_getEnergy.invokeAsync(self, ((), context))

        def begin_getEnergy(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_getEnergy.begin(self, ((), _response, _ex, _sent, context))

        def end_getEnergy(self, _r):
            return _M_SmartHouse.Robot._op_getEnergy.end(self, _r)

        def getPositionX(self, context=None):
            return _M_SmartHouse.Robot._op_getPositionX.invoke(self, ((), context))

        def getPositionXAsync(self, context=None):
            return _M_SmartHouse.Robot._op_getPositionX.invokeAsync(self, ((), context))

        def begin_getPositionX(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_getPositionX.begin(self, ((), _response, _ex, _sent, context))

        def end_getPositionX(self, _r):
            return _M_SmartHouse.Robot._op_getPositionX.end(self, _r)

        def getPositionY(self, context=None):
            return _M_SmartHouse.Robot._op_getPositionY.invoke(self, ((), context))

        def getPositionYAsync(self, context=None):
            return _M_SmartHouse.Robot._op_getPositionY.invokeAsync(self, ((), context))

        def begin_getPositionY(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_getPositionY.begin(self, ((), _response, _ex, _sent, context))

        def end_getPositionY(self, _r):
            return _M_SmartHouse.Robot._op_getPositionY.end(self, _r)

        def move(self, m, context=None):
            return _M_SmartHouse.Robot._op_move.invoke(self, ((m, ), context))

        def moveAsync(self, m, context=None):
            return _M_SmartHouse.Robot._op_move.invokeAsync(self, ((m, ), context))

        def begin_move(self, m, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_move.begin(self, ((m, ), _response, _ex, _sent, context))

        def end_move(self, _r):
            return _M_SmartHouse.Robot._op_move.end(self, _r)

        def setNewPosition(self, p, context=None):
            return _M_SmartHouse.Robot._op_setNewPosition.invoke(self, ((p, ), context))

        def setNewPositionAsync(self, p, context=None):
            return _M_SmartHouse.Robot._op_setNewPosition.invokeAsync(self, ((p, ), context))

        def begin_setNewPosition(self, p, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_setNewPosition.begin(self, ((p, ), _response, _ex, _sent, context))

        def end_setNewPosition(self, _r):
            return _M_SmartHouse.Robot._op_setNewPosition.end(self, _r)

        def turnOff(self, context=None):
            return _M_SmartHouse.Robot._op_turnOff.invoke(self, ((), context))

        def turnOffAsync(self, context=None):
            return _M_SmartHouse.Robot._op_turnOff.invokeAsync(self, ((), context))

        def begin_turnOff(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_turnOff.begin(self, ((), _response, _ex, _sent, context))

        def end_turnOff(self, _r):
            return _M_SmartHouse.Robot._op_turnOff.end(self, _r)

        def turnOn(self, context=None):
            return _M_SmartHouse.Robot._op_turnOn.invoke(self, ((), context))

        def turnOnAsync(self, context=None):
            return _M_SmartHouse.Robot._op_turnOn.invokeAsync(self, ((), context))

        def begin_turnOn(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_SmartHouse.Robot._op_turnOn.begin(self, ((), _response, _ex, _sent, context))

        def end_turnOn(self, _r):
            return _M_SmartHouse.Robot._op_turnOn.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_SmartHouse.RobotPrx.ice_checkedCast(proxy, '::SmartHouse::Robot', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_SmartHouse.RobotPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::SmartHouse::Robot'
    _M_SmartHouse._t_RobotPrx = IcePy.defineProxy('::SmartHouse::Robot', RobotPrx)

    _M_SmartHouse.RobotPrx = RobotPrx
    del RobotPrx

    _M_SmartHouse.Robot = Ice.createTempClass()
    class Robot(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SmartHouse::Robot')

        def ice_id(self, current=None):
            return '::SmartHouse::Robot'

        @staticmethod
        def ice_staticId():
            return '::SmartHouse::Robot'

        def isActive(self, current=None):
            raise NotImplementedError("servant method 'isActive' not implemented")

        def getEnergy(self, current=None):
            raise NotImplementedError("servant method 'getEnergy' not implemented")

        def getPositionX(self, current=None):
            raise NotImplementedError("servant method 'getPositionX' not implemented")

        def getPositionY(self, current=None):
            raise NotImplementedError("servant method 'getPositionY' not implemented")

        def move(self, m, current=None):
            raise NotImplementedError("servant method 'move' not implemented")

        def setNewPosition(self, p, current=None):
            raise NotImplementedError("servant method 'setNewPosition' not implemented")

        def turnOff(self, current=None):
            raise NotImplementedError("servant method 'turnOff' not implemented")

        def turnOn(self, current=None):
            raise NotImplementedError("servant method 'turnOn' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_SmartHouse._t_RobotDisp)

        __repr__ = __str__

    _M_SmartHouse._t_RobotDisp = IcePy.defineClass('::SmartHouse::Robot', Robot, (), None, ())
    Robot._ice_type = _M_SmartHouse._t_RobotDisp

    Robot._op_isActive = IcePy.Operation('isActive', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())
    Robot._op_getEnergy = IcePy.Operation('getEnergy', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_byte, False, 0), ())
    Robot._op_getPositionX = IcePy.Operation('getPositionX', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_float, False, 0), ())
    Robot._op_getPositionY = IcePy.Operation('getPositionY', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_float, False, 0), ())
    Robot._op_move = IcePy.Operation('move', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHouse._t_Movement, False, 0),), (), None, (_M_SmartHouse._t_OutOfEnergyException, _M_SmartHouse._t_InvalidPositionException, _M_SmartHouse._t_RobotNotActiveException))
    Robot._op_setNewPosition = IcePy.Operation('setNewPosition', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_SmartHouse._t_Position, False, 0),), (), None, (_M_SmartHouse._t_InvalidPositionException, _M_SmartHouse._t_RobotNotActiveException))
    Robot._op_turnOff = IcePy.Operation('turnOff', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    Robot._op_turnOn = IcePy.Operation('turnOn', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_SmartHouse.Robot = Robot
    del Robot

# End of module SmartHouse
